import { FormEvent, useEffect, useState } from 'react'
import { Navigate } from 'react-router-dom'
import { useStore } from '../context'
import { supabase } from '../lib/supabase'
import { listDeliveryOptions, type DeliveryClient, type DeliveryDriver } from '../lib/entregas'

type Row={id:string;name:string;client_id:string;default_driver_id:string|null;origin_address:string;destination_address:string;weekdays:number[];start_date:string;end_date:string;scheduled_time:string;runs_per_day:number;active:boolean}
const days=['Seg','Ter','Qua','Qui','Sex','Sáb','Dom']
export default function Programacoes(){
 const {state}=useStore();const user=state.users.find(x=>x.id===state.sessionUserId)!;const cid=user.companyId
 const [rows,setRows]=useState<Row[]>([]),[clients,setClients]=useState<DeliveryClient[]>([]),[drivers,setDrivers]=useState<DeliveryDriver[]>([]),[msg,setMsg]=useState(''),[err,setErr]=useState('')
 const [f,setF]=useState({name:'',client:'',driver:'',origin:'',destination:'',start:new Date().toISOString().slice(0,10),end:'',time:'09:00',qty:'1',week:['1','2','3','4','5']})
 async function load(){if(!supabase||!cid)return;const [r,o]=await Promise.all([supabase.from('delivery_schedules').select('id,name,client_id,default_driver_id,origin_address,destination_address,weekdays,start_date,end_date,scheduled_time,runs_per_day,active').eq('company_id',cid).order('created_at',{ascending:false}),listDeliveryOptions(cid)]);if(r.error)throw r.error;setRows(r.data as Row[]||[]);setClients(o.clients);setDrivers(o.drivers)}
 useEffect(()=>{void load().catch(e=>setErr(e.message))},[])
 if(user.role!=='dono')return <Navigate to="/entregas" replace/>
 async function save(e:FormEvent){e.preventDefault();if(!supabase||!cid)return;setErr('');const r=await supabase.from('delivery_schedules').insert({company_id:cid,name:f.name,client_id:f.client,default_driver_id:f.driver||null,origin_address:f.origin,destination_address:f.destination,weekdays:f.week.map(Number),start_date:f.start,end_date:f.end,scheduled_time:f.time,runs_per_day:Number(f.qty)}).select('id').single();if(r.error){setErr(r.error.message);return}const g=await supabase.rpc('generate_schedule_deliveries',{p_schedule_id:r.data.id,p_from_date:f.start});if(g.error){setErr(g.error.message);return}setMsg(`${g.data} corridas foram programadas.`);setF({...f,name:'',origin:'',destination:'',end:''});await load()}
 return <div><div className="section-heading"><div><h3>Corridas programadas</h3><p className="muted">Crie lotes recorrentes sem misturar com corridas avulsas.</p></div></div>{msg&&<div className="notice notice-ok">{msg}</div>}{err&&<div className="notice notice-error">{err}</div>}<form className="card cadastro-form" onSubmit={save}><h3>Nova programação</h3><div className="form-grid"><label className="field"><span>Nome</span><input required value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></label><label className="field"><span>Cliente</span><select required value={f.client} onChange={e=>setF({...f,client:e.target.value})}><option value="">Selecione</option>{clients.map(x=><option value={x.id}>{x.company_name||x.name}</option>)}</select></label><label className="field form-span-2"><span>Coleta</span><input required value={f.origin} onChange={e=>setF({...f,origin:e.target.value})}/></label><label className="field form-span-2"><span>Entrega</span><input required value={f.destination} onChange={e=>setF({...f,destination:e.target.value})}/></label><label className="field"><span>Piloto padrão</span><select value={f.driver} onChange={e=>setF({...f,driver:e.target.value})}><option value="">Distribuir depois</option>{drivers.map(x=><option value={x.id}>{x.name}</option>)}</select></label><label className="field"><span>Corridas/dia</span><input type="number" min="1" value={f.qty} onChange={e=>setF({...f,qty:e.target.value})}/></label><label className="field"><span>Início</span><input type="date" required value={f.start} onChange={e=>setF({...f,start:e.target.value})}/></label><label className="field"><span>Fim</span><input type="date" required value={f.end} onChange={e=>setF({...f,end:e.target.value})}/></label><label className="field"><span>Horário</span><input type="time" value={f.time} onChange={e=>setF({...f,time:e.target.value})}/></label><div className="field"><span>Dias</span>{days.map((d,i)=><label className="check-field"><input type="checkbox" checked={f.week.includes(String(i+1))} onChange={()=>setF({...f,week:f.week.includes(String(i+1))?f.week.filter(x=>x!==String(i+1)):[...f.week,String(i+1)]})}/>{d}</label>)}</div></div><button className="btn btn-gold btn-inline">Programar corridas</button></form><div className="card table-card"><table className="table"><thead><tr><th>Programação</th><th>Rota</th><th>Período</th><th>Status</th></tr></thead><tbody>{rows.map(r=><tr><td><strong>{r.name}</strong><div className="muted">{r.runs_per_day}/dia</div></td><td>{r.origin_address}<div className="route-arrow">→ {r.destination_address}</div></td><td>{r.start_date} até {r.end_date}</td><td><span className={r.active?'badge b-ok':'badge b-off'}>{r.active?'Ativa':'Pausada'}</span></td></tr>)}</tbody></table></div></div>
}
